version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    tty: true
    networks:
      - desafio02
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - desafio02
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - app

  db:
    build: 
      context: ./data
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio02db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio02

networks:
  desafio02:
    driver: bridge